// src/dashboard/store-config.ts

import type { StoreConfig } from './shared/store-meta.js';
import type { StoreName } from './shared/store-types.js';

export const STORE_CONFIG: Record<StoreName, StoreConfig> = {
  profile: {
    name: 'profile', table: 'profile', primaryKey: ['key'],
    columns: [
      { key: 'key', label: 'Key', type: 'string' },
      { key: 'value', label: 'Value', type: 'string', truncateAt: 200 },
      { key: 'updated_at', label: 'Updated', type: 'timestamp' },
    ],
    filters: [],
    sortable: ['key', 'updated_at'],
    defaultSort: { key: 'key', dir: 'asc' },
    charts: [],
    fts: false,
  },
  preferences: {
    name: 'preferences', table: 'preferences', primaryKey: ['kind', 'key'],
    columns: [
      { key: 'kind', label: 'Kind', type: 'enum' },
      { key: 'key', label: 'Key', type: 'string' },
      { key: 'value', label: 'Value', type: 'string', truncateAt: 200 },
      { key: 'updated_at', label: 'Updated', type: 'timestamp' },
    ],
    filters: [{ key: 'kind', type: 'enum', options: ['rule', 'style'] }],
    sortable: ['kind', 'key', 'updated_at'],
    defaultSort: { key: 'updated_at', dir: 'desc' },
    charts: [],
    fts: false,
  },
  knowledge: {
    name: 'knowledge', table: 'knowledge', primaryKey: ['category', 'key'],
    columns: [
      { key: 'category', label: 'Category', type: 'enum' },
      { key: 'key', label: 'Key', type: 'string' },
      { key: 'value', label: 'Value', type: 'string', truncateAt: 200 },
      { key: 'updated_at', label: 'Updated', type: 'timestamp' },
    ],
    filters: [{
      key: 'category', type: 'enum',
      options: ['identity', 'person', 'routine', 'context', 'insight'],
    }],
    sortable: ['category', 'key', 'updated_at'],
    defaultSort: { key: 'updated_at', dir: 'desc' },
    charts: [{ id: 'count_by_category', label: 'Entries per category', type: 'donut' }],
    fts: true,
  },
  journal: {
    name: 'journal', table: 'journal', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'string', width: 80 },
      { key: 'content', label: 'Content', type: 'string', truncateAt: 300 },
      { key: 'event_date', label: 'Event date', type: 'string' },
      { key: 'created_at', label: 'Created', type: 'timestamp' },
    ],
    filters: [
      { key: 'event_date', type: 'date-range' },
      { key: 'created_at', type: 'date-range' },
    ],
    sortable: ['created_at', 'event_date'],
    defaultSort: { key: 'created_at', dir: 'desc' },
    charts: [{ id: 'count_by_week', label: 'Entries per week', type: 'bar' }],
    fts: false,
  },
  tasks: {
    name: 'tasks', table: 'tasks', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'string', width: 80 },
      { key: 'title', label: 'Title', type: 'string', truncateAt: 200 },
      { key: 'status', label: 'Status', type: 'enum' },
      { key: 'trigger_type', label: 'Trigger', type: 'enum' },
      { key: 'due_date', label: 'Due', type: 'string' },
      { key: 'updated_at', label: 'Updated', type: 'timestamp' },
    ],
    filters: [
      { key: 'status', type: 'enum', options: ['pending', 'done', 'cancelled'] },
      { key: 'trigger_type', type: 'enum', options: ['time', 'event', 'always'] },
      { key: 'due_date', type: 'date-range' },
    ],
    sortable: ['status', 'due_date', 'updated_at', 'created_at'],
    defaultSort: { key: 'updated_at', dir: 'desc' },
    charts: [{ id: 'count_by_status', label: 'Tasks by status', type: 'donut' }],
    fts: false,
  },
  cronjobs: {
    name: 'cronjobs', table: 'cronjobs', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'string', width: 80 },
      { key: 'type', label: 'Type', type: 'enum' },
      { key: 'status', label: 'Status', type: 'enum' },
      { key: 'schedule_human', label: 'Schedule', type: 'string' },
      { key: 'scheduled_at', label: 'Next fire', type: 'timestamp' },
    ],
    filters: [
      { key: 'type', type: 'enum', options: ['once', 'recurring'] },
      { key: 'status', type: 'enum',
        options: ['PENDING', 'EXECUTING', 'EXECUTED', 'FAILED', 'MISSED', 'ACTIVE', 'COMPLETED'] },
    ],
    sortable: ['scheduled_at', 'status'],
    defaultSort: { key: 'scheduled_at', dir: 'asc' },
    charts: [{ id: 'count_by_status', label: 'Cronjobs by status', type: 'donut' }],
    fts: false,
  },
  messages: {
    name: 'messages', table: 'messages', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'string', width: 200 },
      { key: 'gateway', label: 'Gateway', type: 'enum' },
      { key: 'sender', label: 'Sender', type: 'enum' },
      { key: 'session_id', label: 'Session', type: 'string', width: 200 },
      { key: 'body', label: 'Body', type: 'string', truncateAt: 300 },
      { key: 'timestamp', label: 'When', type: 'timestamp' },
    ],
    filters: [
      { key: 'gateway', type: 'enum', options: ['console', 'telegram'] },
      { key: 'sender', type: 'enum', options: ['user', 'assistant', 'system'] },
      { key: 'session_id', type: 'string' },
      { key: 'timestamp', type: 'date-range' },
    ],
    sortable: ['timestamp'],
    defaultSort: { key: 'timestamp', dir: 'desc' },
    charts: [{ id: 'count_by_day', label: 'Messages per day', type: 'bar' }],
    fts: true,
  },
  reactions: {
    name: 'reactions', table: 'reactions', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'number', width: 60 },
      { key: 'message_id', label: 'Message', type: 'string', width: 200 },
      { key: 'actor', label: 'Actor', type: 'enum' },
      { key: 'new_emojis', label: 'Emojis', type: 'json' },
      { key: 'timestamp', label: 'When', type: 'timestamp' },
    ],
    filters: [{ key: 'actor', type: 'enum', options: ['user', 'assistant'] }],
    sortable: ['timestamp'],
    defaultSort: { key: 'timestamp', dir: 'desc' },
    charts: [],
    fts: false,
  },
  sessions: {
    name: 'sessions', table: 'sessions', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'number' },
      { key: 'session_id', label: 'Active session', type: 'string' },
      { key: 'updated_at', label: 'Updated', type: 'timestamp' },
    ],
    filters: [],
    sortable: ['updated_at'],
    defaultSort: { key: 'updated_at', dir: 'desc' },
    charts: [],
    fts: false,
  },
  ledger: {
    name: 'ledger', table: 'ledger', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'string', width: 200 },
      { key: 'stream', label: 'Stream', type: 'string' },
      { key: 'tags', label: 'Tags', type: 'string', truncateAt: 100 },
      { key: 'payload', label: 'Payload', type: 'json' },
      { key: 'ts', label: 'When', type: 'timestamp' },
    ],
    filters: [
      { key: 'stream', type: 'string' },
      { key: 'tags', type: 'substring' },
      { key: 'ts', type: 'date-range' },
    ],
    sortable: ['ts', 'stream'],
    defaultSort: { key: 'ts', dir: 'desc' },
    charts: [{ id: 'aggregate_by_stream', label: 'Events per stream', type: 'bar' }],
    fts: false,
  },
  query_costs: {
    name: 'query_costs', table: 'query_costs', primaryKey: ['id'],
    columns: [
      { key: 'id', label: 'ID', type: 'number', width: 60 },
      { key: 'session_id', label: 'Session', type: 'string', width: 200 },
      { key: 'model', label: 'Model', type: 'string' },
      { key: 'input_tokens', label: 'Input', type: 'number' },
      { key: 'output_tokens', label: 'Output', type: 'number' },
      { key: 'actual_cost_usd', label: 'Cost (USD)', type: 'number' },
      { key: 'timestamp', label: 'When', type: 'timestamp' },
    ],
    filters: [
      { key: 'session_id', type: 'string' },
      { key: 'model', type: 'string' },
      { key: 'timestamp', type: 'date-range' },
    ],
    sortable: ['timestamp', 'actual_cost_usd'],
    defaultSort: { key: 'timestamp', dir: 'desc' },
    charts: [{ id: 'cost_by_day', label: 'Cost per day (USD)', type: 'line' }],
    fts: false,
  },
};
